### ISSUE TITLE
fraud: An attacker can send invalid proof with arbitrary high height

### ISSUE THREAD

**Issue by Wondertan** [celestiaorg/go-fraud#35]
This will block verification logic forever and is a DOS attack. 

The solution is to check the current network height and disallow proofs higher than it.

Found together with @nashqueue

**Comment by nashqueue** [comment]
Thinking out loud, What happens if the global height is at k, but the local height is at k - 5 because we are still syncing for example. Do we reject the fraud proof even if we have not watched up yet ? 

Or as a second option. Could there be an attack where I delay the gossip of headers and give the Full node the Fraud proof , but  for some reason the Light Node will receive the Header after the fraud proof ?

**Comment by vgonkivs** [comment]
> Thinking out loud, What happens if the global height is at k, but the local height is at k - 5 because we are still syncing for example. Do we reject the fraud proof even if we have not watched up yet ?

No, we will wait for the height k in the store and verify the fraud proof.

**Comment by vgonkivs** [comment]
> Or as a second option. Could there be an attack where I delay the gossip of headers and give the Full node the Fraud proof , but for some reason the Light Node will receive the Header after the fraud proof ?

Anyway, it will wait for the k height. The point of this fix is to avoid the situation where we have global height k, but an attacker gives us a fraud proof with the height k+100
